# Generated by Django 2.1.3 on 2018-11-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditEntry',
        ),
    ]
